language: java
jdk: 
  - openjdk8
script: 
  - mvn package 
    
cache:
  directories:
  - $HOME/.m2
deploy:
  - provider: lambda
    edge:
      source: couryrr/dpl
      branch: lambda-java-handler
    skip_cleanup: true   
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET
    function_name: "grant-jwt"
    region: "us-east-2"
    role: "arn:aws:iam::052686530403:role/Lambda-Api-Manager"
    runtime: "java8"
    module_name: "com.dapper.cloud.function.GrantJwt"
    handler_name: "handleRequest"          
    zip: "${TRAVIS_BUILD_DIR}/grant-jwt/target/grant-jwt-0.0.1-SNAPSHOT.jar"
    memory_size: 512
    timeout: 15
  - provider: lambda
    skip_cleanup: true
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET
    function_name: "verify-jwt"
    region: "us-east-2"
    role: "arn:aws:iam::052686530403:role/Lambda-Api-Manager"
    runtime: "java8"
    module_name: "com.dapper.cloud.function.VerifyJwt"
    handler_name: "handleRequest"
    zip: "${TRAVIS_BUILD_DIR}/verify-jwt/target/verify-jwt-0.0.1-SNAPSHOT.jar"
    memory_size: 512
    timeout: 15


